mother: saucer.png \
    transwarp.png \
    escort.png \
    scout.png \
    command.png \
    main.png \
    transwarp-full.png \
    battle-separation.png \
    scout-separation.png \
    aux-separation.png \
    command-separation.png \
    escort-separation.png \
    full-separation.png \
    normal-separation.png 

transwarp.png: ../../src/lib/util.scad \
    ../../src/mother/mlib.scad \
    ../../src/mother/transwarp.scad
	../../bin/render.sh \
	    -i ../../src/mother/transwarp.scad \
	    -p transwarp.png \
	    -t Tomorrow

escort-separation.png: ../../src/lib/util.scad \
    ../../src/mother/mlib.scad \
    ../../src/mother/escort-separation.scad
	../../bin/render.sh \
	    -i ../../src/mother/escort-separation.scad \
	    -p escort-separation.png \
	    -c "-423.55,0,18.72,90,0,0,3064" \
	    -t Tomorrow

transwarp-full.png: ../../src/lib/util.scad \
    ../../src/mother/mlib.scad \
    ../../src/mother/transwarp-full.scad
	../../bin/render.sh \
	    -i ../../src/mother/transwarp-full.scad \
	    -p transwarp-full.png \
	    -t Tomorrow

transwarp-escort.png: ../../src/lib/util.scad \
    ../../src/mother/mlib.scad \
    ../../src/mother/transwarp-escort.scad
	../../bin/render.sh \
	    -i ../../src/mother/transwarp-escort.scad \
	    -p transwarp-escort.png \
	    -c "-224.52,0,2.65,136.9,0,41.8,2173" \
	    -t Tomorrow

dread-scout.png: ../../src/lib/util.scad \
    ../../src/mother/mlib.scad \
    ../../src/mother/dread-scout.scad
	../../bin/render.sh \
	    -i ../../src/mother/dread-scout.scad \
	    -p dread-scout.png \
	    -t Sunset

scout.png: ../../src/lib/util.scad \
    ../../src/mother/mlib.scad \
    ../../src/mother/scout.scad
	../../bin/render.sh \
	    -i ../../src/mother/scout.scad \
	    -p scout.png \
	    -t Tomorrow

command.png: ../../src/lib/util.scad \
    ../../src/mother/mlib.scad \
    ../../src/mother/command.scad
	../../bin/render.sh \
	    -i ../../src/mother/command.scad \
	    -p command.png \
	    -t Tomorrow

battle-separation.png: ../../src/lib/util.scad \
    ../../src/mother/mlib.scad \
    ../../src/mother/battle-separation.scad
	../../bin/render.sh \
	    -i ../../src/mother/battle-separation.scad \
	    -p battle-separation.png \
	    -c "-423.55,0,30.79,90,0,0,3814" \
	    -t Tomorrow

scout-separation.png: ../../src/lib/util.scad \
    ../../src/mother/mlib.scad \
    ../../src/mother/scout-separation.scad
	../../bin/render.sh \
	    -i ../../src/mother/scout-separation.scad \
	    -p scout-separation.png \
	    -c "-119.74,-63.73,-19.55,96.3,0,178.3,1646" \
	    -t Tomorrow

aux-separation.png: ../../src/lib/util.scad \
    ../../src/mother/mlib.scad \
    ../../src/mother/aux-separation.scad
	../../bin/render.sh \
	    -i ../../src/mother/aux-separation.scad \
#	    -p aux-separation.png \
#	    -c "-423.55,0,68.29,90,0,0,3087" \
#	    -t Tomorrow

command-separation.png: ../../src/lib/util.scad \
    ../../src/mother/mlib.scad \
    ../../src/mother/command-separation.scad
	../../bin/render.sh \
	    -i ../../src/mother/command-separation.scad \
	    -p command-separation.png \
	    -c "-423.55,0,80.79,77.4,0,7.7,3099" \
	    -t Tomorrow

dread-saucer.png: ../../src/lib/util.scad \
    ../../src/mother/mlib.scad \
    ../../src/mother/dread-saucer.scad
	../../bin/render.sh \
	    -i ../../src/mother/dread-saucer.scad \
	    -p dread-saucer.png \
	    -t Sunset

saucer.png: ../../src/lib/util.scad \
    ../../src/mother/mlib.scad \
    ../../src/mother/saucer.scad
	../../bin/render.sh \
	    -i ../../src/mother/saucer.scad \
	    -p saucer.png \
	    -t Tomorrow

escort.png: ../../src/lib/util.scad \
    ../../src/mother/mlib.scad \
    ../../src/mother/escort.scad
	../../bin/render.sh \
	    -i ../../src/mother/escort.scad \
	    -p escort.png \
	    -c "-0.95,-5.9,2.74,139.7,0,48.1,810" \
	    -t Tomorrow

dreadnaught.png: ../../src/lib/util.scad \
    ../../src/mother/mlib.scad \
    ../../src/mother/dreadnaught.scad
	../../bin/render.sh \
	    -i ../../src/mother/dreadnaught.scad \
	    -p dreadnaught.png \
	    -t Sunset

main.png: ../../src/lib/util.scad \
    ../../src/mother/mlib.scad \
    ../../src/mother/main.scad
	../../bin/render.sh \
	    -i ../../src/mother/main.scad \
	    -p main.png \
	    -c "-423.55,0,29.82,92.1,0,341.6,2474.88" \
	    -t Tomorrow

full-separation.png: ../../src/lib/util.scad \
    ../../src/mother/mlib.scad \
    ../../src/mother/full-separation.scad
	../../bin/render.sh \
	    -i ../../src/mother/full-separation.scad \
	    -p full-separation.png \
	    -c "-423.55,0,68.72,90,0,0,4289" \
	    -t Tomorrow

normal-separation.png: ../../src/lib/util.scad \
    ../../src/mother/mlib.scad \
    ../../src/mother/normal-separation.scad 
	../../bin/render.sh \
	    -i ../../src/mother/normal-separation.scad \
	    -p normal-separation.png \
	    -c "-423.55,0,30.79,90,0,0,4238" \
	    -t Tomorrow

