misc: cruiser.png \
    cruiser2.png \
    cruiser3.png


cruiser.png: ../../src/lib/util.scad ../../src/misc/cruiser.scad
	../../bin/render.sh \
	    -i ../../src/misc/cruiser.scad \
	    -p cruiser.png \
	    -t DeepOcean

cruiser2.png: ../../src/lib/util.scad ../../src/misc/cruiser2.scad
	../../bin/render.sh \
	    -i ../../src/misc/cruiser2.scad \
	    -p cruiser2.png \
	    -c "20.53,42.62,5.09,88.6,0,132.4,343" \
	    -t Cornfield

cruiser3.png: ../../src/lib/util.scad ../../src/misc/cruiser3.scad
	../../bin/render.sh \
	    -i ../../src/misc/cruiser3.scad \
	    -p cruiser3.png \
	    -c "-62.29,0.15,-2.5,98.4,0,221,564" \
	    -t Solarized


