
icp: attack.png \
    diplomat.png \
    runabout.png \
    tactical-shuttle.png \
    science.png \
    explorer.png \
    destroyer.png \
    diplomat.png \
    long-yacht.png \
    observer.png \
    yacht.png 

attack.png: ../../src/icp/attack.scad \
    ../../src/lib/util.scad \
    ../../src/icp/icp.scad
	../../bin/render.sh \
	    -i ../../src/icp/attack.scad \
	    -p attack.png \
	    -t Sunset

explorer.png: ../../src/icp/explorer.scad \
    ../../src/lib/util.scad \
    ../../src/icp/icp.scad
	../../bin/render.sh \
	    -i ../../src/icp/explorer.scad \
	    -p explorer.png \
	    -t Tomorrow

observer.png: ../../src/icp/observer.scad \
    ../../src/lib/util.scad \
    ../../src/icp/icp.scad
	../../bin/render.sh \
	    -i ../../src/icp/observer.scad \
	    -p observer.png \
	    -t "Tomorrow Night"

destroyer.png: ../../src/icp/destroyer.scad \
    ../../src/lib/util.scad \
    ../../src/icp/icp.scad
	../../bin/render.sh \
	    -i ../../src/icp/destroyer.scad \
	    -p destroyer.png \
	    -t Sunset

yacht.png: ../../src/icp/yacht.scad ../../src/lib/util.scad 
	../../bin/render.sh \
	    -i ../../src/icp/yacht.scad \
	    -p yacht.png \
	    -t Starnight

long-yacht.png: ../../src/icp/long-yacht.scad ../../src/lib/util.scad 
	../../bin/render.sh \
	    -i ../../src/icp/long-yacht.scad \
	    -p long-yacht.png \
	    -t DeepOcean

runabout.png: ../../src/icp/runabout.scad ../../src/lib/util.scad
	../../bin/render.sh \
	    -i ../../src/icp/runabout.scad \
	    -p runabout.png \
	    -t Tomorrow

tactical-shuttle.png: ../../src/icp/tactical-runabout.scad \
    ../../src/lib/util.scad
	../../bin/render.sh \
	    -i ../../src/icp/tactical-runabout.scad \
	    -p tactical-shuttle.png \
	    -t Solarized

science.png: ../../src/icp/science.scad \
    ../../src/lib/util.scad \
    ../../src/icp/icp.scad
	../../bin/render.sh \
	    -i ../../src/icp/science.scad \
	    -p science.png \
	    -t Nature

diplomat.png: ../../src/icp/diplomat.scad \
    ../../src/lib/util.scad \
    ../../src/icp/icp.scad
	../../bin/render.sh \
	    -i ../../src/icp/diplomat.scad \
	    -p diplomat.png \
	    -t Metallic
