macs: shuttlepod.png \
    shuttle.png \
    small-runabout.png \
    cutter.png \
    heavy-runabout.png \
    hospital.png \
    small-pod.png \
    fighter.png \
    tactical-runabout.png \
    large-warp-harness.png \
    disk.png \
    extension.png \
    habitat.png \
    tactical-harness.png \
    small-warp-harness.png \
    freighter.png


fighter.png: ../../src/macs/macs.scad ../../src/lib/util.scad \
    ../../src/macs/fighter.scad
	../../bin/render.sh \
	    -i ../../src/macs/fighter.scad \
	    -p fighter.png \
	    -t BeforeDawn

small-pod.png: ../../src/macs/macs.scad ../../src/lib/util.scad \
    ../../src/macs/small-pod.scad
	../../bin/render.sh \
	    -i ../../src/macs/small-pod.scad \
	    -p small-pod.png \
	    -t BeforeDawn

tactical-runabout.png: ../../src/macs/macs.scad ../../src/lib/util.scad \
    ../../src/macs/tactical-runabout.scad
	../../bin/render.sh \
	    -i ../../src/macs/tactical-runabout.scad \
	    -p tactical-runabout.png \
	    -t BeforeDawn

tactical-harness.png: ../../src/macs/tactical-harness.scad \
    ../../src/lib/util.scad ../../src/macs/macs.scad
	../../bin/render.sh \
	    -i ../../src/macs/tactical-harness.scad \
	    -t BeforeDawn \
	    -p tactical-harness.png

large-warp-harness.png: ../../src/macs/large-warp-harness.scad \
    ../../src/lib/util.scad ../../src/macs/macs.scad
	../../bin/render.sh \
	    -i ../../src/macs/large-warp-harness.scad \
	    -t BeforeDawn \
	    -p large-warp-harness.png

disk.png: ../../src/macs/disk.scad \
    ../../src/lib/util.scad ../../src/macs/macs.scad
	../../bin/render.sh \
	    -i ../../src/macs/disk.scad \
	    -t BeforeDawn \
	    -p disk.png

extension.png: ../../src/macs/extension.scad \
    ../../src/lib/util.scad ../../src/macs/macs.scad
	../../bin/render.sh \
	    -i ../../src/macs/extension.scad \
	    -t BeforeDawn \
	    -p extension.png

habitat.png: ../../src/macs/habitat.scad \
    ../../src/lib/util.scad ../../src/macs/macs.scad
	../../bin/render.sh \
	    -i ../../src/macs/habitat.scad \
	    -t BeforeDawn \
	    -p habitat.png

small-warp-harness.png: ../../src/macs/small-warp-harness.scad \
    ../../src/lib/util.scad ../../src/macs/macs.scad
	../../bin/render.sh \
	    -i ../../src/macs/small-warp-harness.scad \
	    -t BeforeDawn \
	    -p small-warp-harness.png

shuttlepod.png: ../../src/macs/macs.scad ../../src/macs/shuttlepod.scad \
    ../../src/lib/util.scad
	../../bin/render.sh \
	    -i ../../src/macs/shuttlepod.scad \
	    -p pod.png \
	    -t BeforeDawn

shuttle.png: ../../src/macs/macs.scad ../../src/lib/util.scad \
    ../../src/macs/shuttle.scad
	../../bin/render.sh \
	    -i ../../src/macs/shuttle.scad \
	    -p shuttle.png \
	    -t BeforeDawn

small-runabout.png: ../../src/macs/macs.scad ../../src/lib/util.scad \
    ../../src/macs/runabout.scad
	../../bin/render.sh \
	    -i ../../src/macs/runabout.scad \
	    -p small-runabout.png \
	    -t BeforeDawn

cutter.png: ../../src/macs/macs.scad ../../src/lib/util.scad \
    ../../src/macs/cutter.scad
	../../bin/render.sh \
	    -i ../../src/macs/cutter.scad \
	    -p cutter.png \
	    -t BeforeDawn

heavy-runabout.png: ../../src/macs/macs.scad ../../src/lib/util.scad \
    ../../src/macs/heavy.scad
	../../bin/render.sh \
	    -i ../../src/macs/heavy.scad \
	    -p heavy-runabout.png \
	    -t BeforeDawn

hospital.png: ../../src/macs/macs.scad ../../src/lib/util.scad \
    ../../src/macs/hospital.scad
	../../bin/render.sh \
	    -i ../../src/macs/hospital.scad \
	    -p hospital.png \
	    -t Metallic

freighter.png: ../../src/macs/macs.scad ../../src/lib/util.scad \
    ../../src/macs/freighter.scad
	../../bin/render.sh \
	    -i ../../src/macs/freighter.scad \
	    -p freighter.png \
	    -t Nature


