name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        apt install -y flatpak imagemagick;
        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo;
        flatpak install flathub org.openscad.OpenSCAD;
      
      
    - name: Install
      run: make
      
    - name: Run check
      run: make check
      
    - name: Run distcheck
      run: make distcheck
