name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
          
    - name: dummy exit
      run: echo
    
    - name: Install dependencies
      run: |
        sudo apt install -y xvfb imagemagick openscad;
      
    - name: Install
      run: |
        Xvfb :5 -screen 0 800x600x24 &
        export DISPLAY=:5
        make
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "generated"
        git push      
        
